# Programación para la Bioinformática

Unidad 3: Librerías científicas en Python - NumPy
-------------------------------------------------

### Instrucciones de uso
A continuación se presentarán explicaciones y ejemplos de uso de la librería NumPy. Recordad que podéis ir ejecutando los ejemplos para obtener sus resultados.

### Primeros pasos
Vamos a importar la librería:

In [2]:
# En la siguiente línea, importamos NumPy y le damos un nombre más corto 
# para que nos sea más cómodo hacer las llamadas
import numpy as np

En NumPy, el objeto básico se trata de una lista multidimensional de números (normalmente) del mismo tipo

In [3]:
# Ejemplo básico, un punto en el espacio 3D:
p = np.array([1, 2, 3])

En NumPy, a las dimensiones se les conoce con el nombre de ejes (*axes*) y al número de ejes, rango (*rank*). *array* es un alias para referirse al tipo de objeto *numpy.ndarray*.

Algunas propiedades importantes de los arrays son las siguientes:
* **ndarray.ndim**: el número de ejes del objeto array (matriz)
* **ndarray.shape**: Una tupla de números enteros indicando la longitud de las dimensiones de la matriz
* **ndarray.size**: el número total de elementos de la matriz

In [4]:
# Vamos a crear una matrix bidimensional 3x2 (tres filas, dos columnas)
a = np.arange(3*2) # Creamos un array unidimensional de 6 elementos
print('Array unidimensional:')
print(a)
a = a.reshape(3,2) # Le damos "forma" de matrix 3x2
print('Matriz 3x2:')
print(a)

Array unidimensional:
[0 1 2 3 4 5]
Matriz 3x2:
[[0 1]
 [2 3]
 [4 5]]


In [5]:
# La dimensión es 2
a.ndim

2

In [6]:
# Longitud de las dimensiones
a.shape

(3, 2)

In [7]:
# El número total de elementos
a.size

6

A la hora de crear arrays, tenemos diferentes opciones:

In [8]:
# Creamos un array (vector) de diez elementos:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Podemos cambiar cualquiera de los valores de este vector accediendo a su posición:
z[4] = 5.0
z[-1] = 0.1
print(z)

[0.  0.  0.  0.  5.  0.  0.  0.  0.  0.1]


In [10]:
# La función arange nos permite definir diferentes opciones, como el punto de inicio y el de fin:
a = np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [11]:
# El último argumento nos permite utilizar un paso de 2:
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [12]:
# Podemos crear arrays desde listas de Python de varias dimensiones:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


### Operaciones con matrices
NumPy implementa todas las operaciones habituales con matrices

In [13]:
A = np.array([[1,0], [0,1]])
B = np.array([[1,2], [3,4]])

In [14]:
# Suma de matrices
print(A+B)

[[2 2]
 [3 5]]


In [15]:
# Resta de matrices
print(A-B)

[[ 0 -2]
 [-3 -3]]


In [16]:
# Multiplicación elemento por elemento
print(A*B)

[[1 0]
 [0 4]]


In [17]:
# Multiplicación de matrices
print(A.dot(B))

[[1 2]
 [3 4]]


In [18]:
# Potencia
print(B**2)

[[ 1  4]
 [ 9 16]]


### *Slicing* e iteración
Los arrays en NumPy soportan la técnica de *slicing* de Python:


In [19]:
# Definimos un array de 0 a 9
a = np.arange(10)
# Obtenemos los 5-2 elementos desde la posición 3 del array (los índices empiezan en 0)
print(a[2:5])

[2 3 4]


In [20]:
# Todos los elementos a partir de la tercera posición
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Podemos iterar por cada elemento del array:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
# Definamos ahora un array multidimensional
A = np.arange(18).reshape(6,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [23]:
# Obtenemos hasta la quinta fila
print(A[:5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [24]:
# Igualamos todos los elementos a 0 (el operador ... añade todos los : necesarios)
A[...] = 0
print(A)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Ejemplo: El juego de la vida de Conway
El juego de la vida es un ejemplo clásico de autómata celular creado en 1970 por el famoso matemático John H. Conway. 
En el problema clásico, se representan en una matriz bidimensional células que vivirán o morirán dependiendo del número de vecinos en un determinado paso de la simulación. Cada célula tiene 8 vecinos (las casillas adyacentes en un tablero bidimensional) y puede estar viva (1) o muerta (0). Las reglas clásicas entre transición vida/muerte son las siguientes:

* Una célula muerta con exactamente 3 células vecinas vivas al turno siguiente estará viva.
* Una célula viva con 2 o 3 células vecinas vivas sigue viva, en otro caso muere o permanece muerta (soledad en caso de un número menor a 2, superpoblación si es mayor a 3).

Este problema (o juego) tiene muchas variantes dependiendo de las condiciones iniciales, si el tablero (o mundo) tiene bordes o no, o si bien las reglas de vida o muerte son alteradas.

A continuación tenéis un ejemplo del juego clásico implementado en NumPy:

In [25]:
# Autor: Nicolas Rougier
# Fuente: http://www.labri.fr/perso/nrougier/teaching/numpy.100/

SIZE = 20
STEPS =10

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

# Creamos un tablero con células vivas o muertas de forma aleatoria
Z = np.random.randint(0,2,(SIZE, SIZE))
# Simulamos durante los pasos indicados
for i in range(STEPS):
    Z = iterate(Z)
# Mostramos el tablero en el paso final
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0]
 [0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 0 0]
 [0 0 1 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
